# Generated by Django 3.2.8 on 2021-11-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'ingredients'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='recipe_author',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='spices',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='ml_oz',
        ),
        migrations.AddField(
            model_name='quantity',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cocktails_app.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantity',
            name='spices',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quantity',
            name='volume',
            field=models.IntegerField(choices=[('ml', 'ml'), ('oz', 'oz'), ('tsp', 'tsp.'), ('tbsp', 'tbsp.')], null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('shaking', 'Shaking'), ('stir', 'Stir'), ('blend', 'Blend')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
