# Generated by Django 3.2.8 on 2021-11-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0002_auto_20211115_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
